version: '3'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017
    s3:
        image: minio/minio
        ports:
            - 9000
            - 9001:9001
        environment:
            - MINIO_ROOT_USER=ludvig
            - MINIO_ROOT_PASSWORD=castillo
        command: server /data --console-address :9001
    luigi:
        build: ./luigi
        image: luigi
        ports:
            - 5001
        depends_on:
            - mongo
        environment:
            - PORT=5001
            - MONGO_URI=mongodb://mongo:27017/ludvig
        command: npm run prod  
    wario:
        build: ./wario
        image: wario
        ports:
            - 3001
        depends_on:
            - mongo
            - luigi
        environment:
            - PORT=3001
            - LUIGI_URI=ws://luigi:5001
            - ORIGIN=http://gigabossofswag.cse356.compas.cs.stonybrook.edu
            - EMAIL_ADDRESS=zestysidewalk123test@gmail.com
            - EMAIL_PASSWORD=SpicyChicken123!
        command: npm run prod
    rowlet:
        build: ./rowlet
        image: rowlet
        ports:
            - 80:80
        depends_on:
            - wario
    # using multistage dockerfile in rowlet for now
    # nginx:
    #     build: ./nginx
    #     image: nginx
    #     depends_on:
    #         - rowlet
    #     ports:
    #         - 80:80
