version: '3'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017
    luigi:
        build: ./luigi
        image: luigi
        volumes:
            - ./luigi:/usr/luigi
        ports:
            - 5001:5001
        depends_on:
            - mongo
        environment:
            - PORT=5001
            - MONGO_URI=mongodb://mongo:27017/ludvig
        command: npm run dev  
    wario:
        build: ./wario
        image: wario
        volumes:
            - ./wario:/usr/wario
        ports:
            - 3001:3001
        depends_on:
            - mongo
            - luigi
        environment:
            - PORT=3001
            - LUIGI_URI=ws://luigi:5001
        command: npm run dev
    rowlet:
        build: 
            context: ./rowlet
            dockerfile: Dockerfile.development
        image: rowlet
        volumes:
            - ./rowlet:/usr/rowlet
        ports:
            - 3000:3000
        depends_on:
            - wario
        command: npm start
