version: '3'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 49153:27017
    s3:
        image: minio/minio
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ROOT_USER=ludvig
            - MINIO_ROOT_PASSWORD=castillo
        command: server /data --console-address :9001
    # luigi:
    #     build: ./luigi
    #     image: luigi
    #     ports:
    #         - 49154:5001
    #     depends_on:
    #         - mongo
    #     environment:
    #         - PORT=5001
    #         - MONGO_URI=mongodb://mongo:27017/ludvig
    #     command: npm run prod  
    # Running into issues trying to connect container with SMTP server :/, esp. w port 25 complications w/ UpCloud
    # wario:
    #     build: ./wario
    #     image: wario
    #     ports:
    #         - 3001
    #     depends_on:
    #         - mongo
    #         - luigi
    #     environment:
    #         - PORT=3001
    #         - LUIGI_URI=ws://luigi:5001
    #         - ORIGIN=http://gigabossofswag.cse356.compas.cs.stonybrook.edu
    #     command: npm run prod
    # rowlet:
    #     build: ./rowlet
    #     image: rowlet
    #     ports:
    #         - 80:80
    #     environment:
    #         - REACT_APP_WARIO_URI=http://gigabossofswag.cse356.compas.cs.stonybrook.edu
    #         - REACT_APP_S3_ACCESS_URI=http://gigabossofswag.cse356.compas.cs.stonybrook.edu/media/access
        # depends_on:
        #     - wario
    # using multistage dockerfile in rowlet for now
    # nginx:
    #     build: ./nginx
    #     image: nginx
    #     depends_on:
    #         - rowlet
    #     ports:
    #         - 80:80
