version: '3'

services:
    mongo:
        image: mongo
        ports:
            - 49153:27017
    elasticsearch:
        image: elasticsearch:8.1.2
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - "discovery.type=single-node"
    s3:
        image: minio/minio
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ROOT_USER=ludvig
            - MINIO_ROOT_PASSWORD=castillo
        command: server /data --console-address :9001
    luigi:
        build: ./luigi
        image: luigi
        volumes:
            - ./luigi:/usr/luigi
        ports:
            - 49154:5001
        depends_on:
            - mongo
        environment:
            - PORT=5001
            - MONGO_URI=mongodb://mongo:27017/ludvig
        command: npm run dev  
    wario:
        build: ./wario
        image: wario
        volumes:
            - ./wario:/usr/wario
        ports:
            - 3001:3001
        depends_on:
            - mongo
            - luigi
            - s3
        environment:
            - PORT=3001
            - LUIGI_URI=ws://luigi:5001
            - ORIGIN=http://localhost:3001
            - MONGO_URI=mongodb://mongo:27017/ludvig
            - S3_URI=s3
        command: npm run dev
    rowlet-dev:
        build: 
            context: ./rowlet
            dockerfile: Dockerfile.development
        image: rowlet-dev
        volumes:
            - ./rowlet:/usr/rowlet
        ports:
            - 3000:3000
        environment:
            - REACT_APP_WARIO_URI=http://localhost:3001
            - REACT_APP_S3_ACCESS_URI=http://localhost:3001/media/access
        command: npm start
