FROM node:17.8.0

# Set service directory
WORKDIR /usr/rowlet

# Install Dependencies
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

# Copy over repo
COPY . .

ENV REACT_APP_WARIO_URI http://localhost:3001
ENV REACT_APP_S3_ACCESS_URI http://localhost:9000/doc-media