FROM node:17.8.0

# Set service directory
WORKDIR /usr/rowlet

# Install Dependencies
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

# Copy over repo
COPY . .